set nocompatible

let s:root = fnamemodify(expand('<sfile>:p'), ':h:h')
execute 'set runtimepath^=' . fnameescape(s:root)
execute 'runtime plugin/lan.vim'

function! s:fail(msg) abort
  if exists('s:orig_tags')
    call writefile(s:orig_tags, s:root . '/doc/tags')
  else
    call delete(s:root . '/doc/tags')
  endif
  echoerr a:msg
  cquit 1
endfunction

let s:orig_tags = filereadable(s:root . '/doc/tags') ? readfile(s:root . '/doc/tags') : []
call delete(s:root . '/doc/tags')
call lan#setup({})

if !filereadable(s:root . '/doc/tags')
  call s:fail('lan regression: doc/tags was not generated by setup()')
endif

try
  execute 'help lan.vim'
catch
  call s:fail('lan regression: :help lan.vim failed: ' . v:exception)
endtry

if expand('%:t') !=# 'lan.txt'
  call s:fail('lan regression: :help lan.vim opened ' . expand('%:t') . ' (expected lan.txt)')
endif

if !empty(s:orig_tags)
  call writefile(s:orig_tags, s:root . '/doc/tags')
else
  call delete(s:root . '/doc/tags')
endif
cquit 0
